language: python
python: 2.7
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py34
cache:
  directories:
    - $HOME/.cache/pip
install: pip install tox
script: tox
os:
  - linux
before_install:
  - sudo apt-get install locate
  - sudo service postgresql stop
  - sudo apt-get remove postgresql
  - sudo apt-get install postgresql || true
  - sudo updatedb
dist: trusty
addons:
  postgresql: "9.5"
