language: python
python: 2.7
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py34
cache:
  directories:
    - $HOME/.cache/pip
install: pip install tox
script: tox
os:
  - linux
  - osx
before_install:
  - sudo apt-get install locate
  - sudo apt-get install postgresql
  - sudo updatedb
